/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bonschallenge;

import java.awt.BorderLayout;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author Josh
 */
public class BonsFrame extends javax.swing.JFrame {
    public static final int DEVELOPER_MODE = 10;
    public static final int NORMAL_MODE = 1;
    private int currentGameMode;
    private final DeveloperMode dev;
    protected static JPanel board;
    protected static int frameWidth, frameHeight;
    
    private class MyDispatcher implements KeyEventDispatcher {
        @Override
        public boolean dispatchKeyEvent(KeyEvent e) {
            if (e.getID() == KeyEvent.KEY_PRESSED) {
            	if(e.getKeyCode() == KeyEvent.VK_F1){
                    if(currentGameMode == DEVELOPER_MODE){
                        currentGameMode = NORMAL_MODE;
                        mainLoop();
                    }else{
                        currentGameMode = DEVELOPER_MODE;
                        mainLoop();
                    }
                }else{
                    
                }
            }
            return false;
        }
    }
    /**
     * Creates new form BonsFrame
     */
    public BonsFrame() {
        initComponents();
        KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        manager.addKeyEventDispatcher(new MyDispatcher());
        this.setLayout(new BorderLayout(0,0));
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.repaint();
        jPanel1.setLayout(new BorderLayout(0,0));
        jPanel1.add(jTabbedPane1);
        jPanel1.revalidate();
        jPanel1.repaint();
        dev = new DeveloperMode();
        this.setTitle("Bon's Challenge");
        frameWidth = this.getWidth();
        frameHeight = this.getHeight();
        System.out.println("jPanel2 width: " + jPanel2.getWidth() + " jPanel2 height: " + jPanel2.getHeight());
        jPanel2.addComponentListener(new ComponentAdapter(){
        	@Override
        	public void componentResized(ComponentEvent e){
        		int width = jPanel2.getWidth();
        		int height = jPanel2.getHeight(); 
        		System.out.println("height: " + jPanel2.getHeight() + " frameHeight: " + frameHeight);
        		if(height != frameHeight){
        			frameHeight = height+38;
        			updateSize();
        		}
        		if(currentGameMode == DEVELOPER_MODE){
        			if(width + jPanel1.getWidth() != frameWidth){
        				frameWidth = width + jPanel1.getWidth()+17;
        				updateSize();
        			}
        		}else{
        			if(width != frameWidth){
        				frameWidth = width;
        				updateSize();
        			}
        		}
        	}
        });
        this.addComponentListener(new ComponentAdapter(){
        	@Override
        	public void componentResized(ComponentEvent e){
        		 frameWidth = e.getComponent().getWidth();
                 frameHeight = e.getComponent().getHeight();
        	}
        });
    }
    
    private void updateSize(){
    	this.setSize(frameWidth, frameHeight);
    	this.remove(jPanel1);
    	this.revalidate();
    	this.repaint();
    	this.add(jPanel1, BorderLayout.EAST);
    	this.revalidate();
    	this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedHandler(evt);
            }
        });

        jPanel1.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jButton1.setText("jButton1");
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedHandler(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bonschallenge/plain.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButton1)
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keyPressedHandler(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressedHandler
        /*if(evt.getKeyCode() == KeyEvent.VK_F1){
            if(currentGameMode == DEVELOPER_MODE){
                currentGameMode = NORMAL_MODE;
                mainLoop();
            }else{
                currentGameMode = DEVELOPER_MODE;
                mainLoop();
            }
        }else{
            
        }*/
    }//GEN-LAST:event_keyPressedHandler

    private void mainLoop(){
        if(currentGameMode == DEVELOPER_MODE){
            this.setTitle("Developer Mode");
            jPanel1.setSize(200, 183);
            jPanel1.setVisible(true);
            this.setSize(jPanel1.getWidth()+jPanel2.getWidth(),jPanel2.getHeight());
            System.out.println("developer mode enabled");
        }else if(currentGameMode == NORMAL_MODE){
            this.setTitle("Bon's Challenge");
            jPanel1.setVisible(false);
            this.setSize(jPanel2.getWidth() + 16, jPanel2.getHeight() + 38);
            System.out.println("normal mode enabled");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BonsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BonsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BonsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BonsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BonsFrame().setVisible(true);
            }
        });
    }

    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    protected static javax.swing.JPanel jPanel2;
    protected static javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
